### ISSUE TITLE
Keepmykeys crash 1.18.1, no crashlog.

### ISSUE THREAD

**Issue by agentwolf88** [IamBlueSlime/SlimmyMods#1]
[latest.log](https://github.com/IamBlueSlime/SlimmyMods/files/7796190/latest.log)

**Comment by jeremylvln** [comment]
Hi! Sorry about that.

Without crashlog I don't know if I could do anything, are you sure there is nothing? Even in your installation folder (in case where there are more than one log file, don't know...)

_By the way, I see that you are using the ATLauncher, KeepMyKeys does not have support for looking for existing Minecraft installations with ATLauncher, be assured that I've added it to my todo list :) (It will still work if you have Minecraft vanilla or CurseForge though)._
